name: qernal-arangoqs-build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: rustfmt
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: arangors=trace
        with:
          command: fmt
          args: --all -- --check

      - name: check build (blocking)
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: arangors=trace
        with:
          command: check
          args: --no-default-features --features "rocksdb cluster enterprise blocking" --lib

      - name: check build (reqwest_blocking)
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: arangors=trace
        with:
          command: check
          args: --no-default-features --features "rocksdb cluster enterprise reqwest_blocking" --all

      - name: check build (default features)
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: arangors=trace
        with:
          command: check
          args: --all --bins --examples --tests

      - name: check build (async)
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: arangors=trace
        with:
          command: check
          args: --no-default-features --features "rocksdb cluster enterprise" --lib

      - name: check build (reqwest_async)
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: arangors=trace
        with:
          command: check
          args: --no-default-features --features "rocksdb cluster enterprise reqwest_async" --all

      - name: check build (surf_async)
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: arangors=trace
        with:
          command: check
          args: --no-default-features --features "rocksdb cluster enterprise surf_async" --all


