name: qernal-arangoqs-main

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    uses: ./.github/workflows/build.yaml
  test:
    needs: [build]
    uses: ./.github/workflows/test.yaml
  publish:
    needs: [build, test]
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/publish.yaml
    secrets:
      CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}