name: qernal-arangoqs-publish

on: [push, pull_request]

jobs:
  doc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: doc
        uses: actions-rs/cargo@v1
        env:
          RUSTDOCFLAGS: -Dwarnings
        with:
          command: doc
          args: --all --no-deps

  publish:
    name: Publish Package
    needs: build_and_test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: login
        env:
          CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
        run: cargo login "${CARGO_TOKEN}"
        shell: bash

      - name: publish
        uses: actions-rs/cargo@v1
        with:
          command: publish
