name: qernal-arangoqs-test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Start ArangoDB by docker-compose
        run: |
          docker-compose up -d
          sleep 30
          docker-compose logs

      - name: Set up ArangoDB for test
        run: bash ./.github/scripts/create-db.sh

      - name: test (blocking)
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: arangors=trace
        timeout-minutes: 40
        with:
          command: test
          args: --no-fail-fast --no-default-features --features "rocksdb cluster enterprise blocking" --lib

      - name: test (reqwest_blocking)
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: arangors=trace
        timeout-minutes: 40
        with:
          command: test
          args: --no-fail-fast --no-default-features --features "rocksdb cluster enterprise reqwest_blocking" --all

      - name: tests (default features)
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: arangors=trace
        timeout-minutes: 40
        with:
          command: test
          args: --all --no-fail-fast -- --nocapture

      - name: test (async)
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: arangors=trace
        timeout-minutes: 40
        with:
          command: test
          args: --no-fail-fast --no-default-features --features "rocksdb cluster enterprise" --lib

      - name: test (reqwest_async)
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: arangors=trace
        timeout-minutes: 40
        with:
          command: test
          args: --no-fail-fast --no-default-features --features "rocksdb cluster enterprise reqwest_async" --all

      - name: test (surf_async)
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: arangors=trace
        timeout-minutes: 40
        with:
          command: test
          args: --no-fail-fast --no-default-features --features "rocksdb cluster enterprise surf_async" --all